### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by tjmcclure0501** [hueniverse/oz#60]
https://github.com/Mashape/kong/issues/511

We are currently using oz as the security solution in our framework as we felt it offers the strongest security solution.  We are looking to now implement a technology like Kong - which supports OAuth2.  There was talk about integrating Oz into Kong but it appears this did not happen mainly because there was no complete spec for Oz -see link above.  We could potentially write a Kong plug-in for Oz - however no one wants an unsupported propriety security technology as part of their architecture. 

Is there an intention to complete the Oz spec?  Is there any desire to have Oz integrated with frameworks such as Kong?  Is there a roadmap for this project?

**Comment by AJamesPhillips** [comment]
Hi @tjmcclure0501 , [this article](https://hueniverse.com/auth-to-see-the-wizard-4a7c3572f618) may no longer be accurate but at the time of writing huenverse stated, well I paraphrase:

He wrote a JavaScript module providing a full authentication and authorization solution for building web applications.  He did not write a protocol because the "problem with security protocols is that they are useless without an equally solid implementation. The only point in a protocol is interoperability and I don’t care about interoperability." He just wants to, and with Oz also allows us to, build great and secure web products.

I don't understand the "unsupported propriety [sic] security technology".  Whilst the license mentions yahoo's postmile, the copyright is owned by the contributors.  So it is proprietary but contribute and you become an owner.  Perhaps there is some relevant legalese I'm missing in your jurisdiction?   If so perhaps open a new issue or preferably submit a PR to the license to start a conversation.

Is it dead?  Huenverse interacted with it at least a month ago... I feel like I've misunderstood your point again though.

Re: Complete spec / roadmap.  I believe the implementation is compete.  (And that is the spec)

> integrated with frameworks such as Kong

This would not live in this repo nor in the Kong repo but in a Kong-Oz repo surely?  And I'd have thought this would be very well received.

**Comment by hueniverse** [comment]
I have no intention of writing a specification for oz or hawk. Both projects are working well and cover all my needs. As I find new use cases or bugs, I will publish new versions to address them.
